[package]
name = "neu-arena"
version = "0.1.0"
authors = ["frondeus"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#anymap = "0.12.1"
mopa = "0.2.2"